controller_manager:
  ros__parameters:
    update_rate: 100  # Hz

    wheel_controller:
      type: velocity_controllers/JointGroupVelocityController

    servo_controller:
      type: joint_trajectory_controller/JointTrajectoryController

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

#---------------wheel_velocity_controller----------------#
wheel_controller:
  ros__parameters:
    joints:
      - mid_right_wheel_joint
      - mid_left_wheel_joint
      - front_right_wheel_joint
      - front_left_wheel_joint
      - back_right_wheel_joint
      - back_left_wheel_joint
    command_joints:
      - mid_right_wheel_joint
      - mid_left_wheel_joint
      - front_right_wheel_joint
      - front_left_wheel_joint
      - back_right_wheel_joint
      - back_left_wheel_joint
    command_interfaces:
      - velocity
      - position
    state_interfaces:
      - position
      - velocity


#---------------servo_velocity_controller----------------#

servo_controller:
  ros__parameters:
    allow_nonzero_velocity_at_trajectory_end: true
    joints:
      - front_right_corner_joint
      - front_left_corner_joint
      - back_right_corner_joint
      - back_left_corner_joint
    interface_name: position
    command_interfaces:
      - position
      - velocity
    command_joints:
      - front_right_corner_joint
      - front_left_corner_joint
      - back_right_corner_joint
      - back_left_corner_joint
    state_interfaces:
      - position
      - velocity

joint_state_broadcaster:
  ros__parameters:
    joints:
      - front_right_corner_joint
      - front_left_corner_joint
      - back_right_corner_joint
      - back_left_corner_joint
      - mid_right_wheel_joint
      - mid_left_wheel_joint
      - front_right_wheel_joint
      - front_left_wheel_joint
      - back_right_wheel_joint
      - back_left_wheel_joint
    interfaces:
      - position
      - velocity